name: Build MPC-NE

on:
  push:
    branches-ignore:
      - qt6-migration
    paths-ignore:
      - .github/workflows/main.yml
      - '**.txt'
      - '**.md'
      - '**.cmd'
      - '!build.bat'
      - '**.manifest.conf'
      - '**.manifest.template'
      - include/Version.h
  pull_request:
    branches-ignore:
      - qt6-migration
    paths-ignore:
      - .github/workflows/main.yml
      - '**.txt'
      - '**.md'
      - '**.cmd'
      - '!build.bat'
      - '**.vcxproj.filters'
      - '**.manifest.conf'
      - '**.manifest.template'
      - include/Version.h
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022
    timeout-minutes: 120

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Install Visual Studio 2026
        run: |
          $url = "https://aka.ms/vs/18/release/vs_enterprise.exe"
          Invoke-WebRequest -Uri $url -OutFile "vs_enterprise.exe"
          .\vs_enterprise.exe --quiet --wait --norestart --nocache --add Microsoft.VisualStudio.Workload.VCTools --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 --add Microsoft.VisualStudio.Component.Windows11SDK.22000
        shell: pwsh

      - name: Prepare MSYS
        run: |
          curl -sSL https://github.com/Aleksoid1978/MSYS/raw/main/MSYS_MinGW-w64_GCC_1521_x86-x64.7z -o MSYS.7z
          7z x MSYS.7z -oC:\\MSYS
          echo '@ECHO OFF' > environments.bat
          echo 'SET "MPCBE_MSYS=C:\\MSYS"' >> environments.bat
          echo 'SET "MPCBE_MINGW=C:\\MSYS\\mingw"' >> environments.bat
          .\\update_gcc.bat
        shell: pwsh

      - name: Clean
        run: |
          .\\build.bat Clean All NoWait VS2026
        shell: pwsh

      - name: Build MPC-NE
        run: |
          .\\build.bat Build Packages NoWait VS2026
        shell: pwsh

      - name: Upload Installer x64
        uses: actions/upload-artifact@v7
        with:
          name: "Installer x64"
          path: _bin/Packages/**/MPC-NE_v*-x64-installer.exe
          compression-level: 0

      - name: Upload Portable x64
        uses: actions/upload-artifact@v7
        with:
          name: "Portable x64"
          path: _bin/Packages/**/MPC-NE_v*-x64.7z
          compression-level: 0