name: Build MPC-NE

on:
  push:
    branches-ignore:
      - qt6-migration
    paths-ignore:
      - .github/workflows/main.yml
      - '**.txt'
      - '**.md'
      - '**.cmd'
      - '!build.bat'
      - '**.manifest.conf'
      - '**.manifest.template'
      - include/Version.h
  pull_request:
    branches-ignore:
      - qt6-migration
    paths-ignore:
      - .github/workflows/main.yml
      - '**.txt'
      - '**.md'
      - '**.cmd'
      - '!build.bat'
      - '**.vcxproj.filters'
      - '**.manifest.conf'
      - '**.manifest.template'
      - include/Version.h

jobs:
  build:
    runs-on: windows-2022
    timeout-minutes: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Prepare MSYS
        run: |
          curl -sSL https://github.com/Aleksoid1978/MSYS/raw/main/MSYS_MinGW-w64_GCC_1521_x86-x64.7z -o MSYS.7z
          7z x MSYS.7z -oC:\\MSYS
          echo '@ECHO OFF' > environments.bat
          echo 'SET "MPCNE_MSYS=C:\\MSYS"' >> environments.bat
          echo 'SET "MPCNE_MINGW=C:\\MSYS\\mingw"' >> environments.bat
          .\\update_gcc.bat
        shell: pwsh

      - name: Clean
        run: |
          .\\build.bat Clean All NoWait
        shell: pwsh

      - name: Build MPC-NE
        run: |
          .\\build.bat Build Packages NoWait
        shell: pwsh

      - name: Upload Installer amd64
        uses: actions/upload-artifact@v7
        with:
          name: "Installer amd64"
          path: _bin/Packages/**/MPC-NE_v*-amd64-installer.exe
          compression-level: 0

      - name: Upload Portable amd64
        uses: actions/upload-artifact@v7
        with:
          name: "Portable amd64"
          path: _bin/Packages/**/MPC-NE_v*-amd64.7z
          compression-level: 0

      - name: Upload Installer arm64
        uses: actions/upload-artifact@v7
        with:
          name: "Installer arm64"
          path: _bin/Packages/**/MPC-NE_v*-arm64-installer.exe
          compression-level: 0

      - name: Upload Portable arm64
        uses: actions/upload-artifact@v7
        with:
          name: "Portable arm64"
          path: _bin/Packages/**/MPC-NE_v*-arm64.7z
          compression-level: 0